# Generated by Django 5.0.6 on 2024-07-12 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Przepis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='SkladnikWPrzepisie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jednostka', models.CharField(max_length=12)),
                ('ilosc', models.IntegerField()),
                ('przepis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przepisy.przepis')),
                ('skladnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przepisy.skladnik')),
            ],
        ),
        migrations.AddField(
            model_name='przepis',
            name='skladniki',
            field=models.ManyToManyField(through='przepisy.SkladnikWPrzepisie', to='przepisy.skladnik'),
        ),
    ]
