# Generated by Django 5.0.6 on 2024-06-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_publisher_magazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='no_pages',
            field=models.IntegerField(default=101),
        ),
    ]
