# Generated by Django 5.0.6 on 2024-06-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_magazine_no_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=7),
        ),
    ]
