# Generated by Django 5.0.6 on 2024-06-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_magazine_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='period2',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly')], default=1),
        ),
    ]
