# Generated by Django 5.0.6 on 2024-06-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_magazine_period2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='period',
        ),
    ]
