# Generated by Django 5.0.6 on 2024-06-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_magazine_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='period2',
            new_name='period',
        ),
    ]
